name: "publish npm"

on: push

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v2
            - name: node
              uses: actions/setup-node@v2
              with:
                  node-version: 20
                  registry-url: https://https://npm.pkg.github.com
            - name: publish
              run: npm publish --access public
              working-directory: master
              env:
                  NODE_AUTH_TOKEN: ${{secrets.npm_token}}
